
[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "U"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "D"
mods = "Shift|Control"

[general]
live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 10

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"

[font.offset]
x = 0
y = 0

[selection]
save_to_clipboard = true
semantic_escape_chars = ''',│`|:"' ()[]{}<>'''

[window]
opacity = 0.8

[colors]
draw_bold_text_with_bright_colors = true

[keyboard]
