#
# manual:
#   https://github.com/alacritty/alacritty/wiki
# template:
#   https://github.com/alacritty/alacritty/blob/master/alacritty.yml
#
# 实时重载配置文件，不用重启测试配置选项
live_config_reload: true

env:
  TERM: xterm-256color

window:
  opacity: 0.8
  # padding:
  #   x: 5
  #   y: 0

draw_bold_text_with_bright_colors: true

# 字体设置为等宽字体，可以用命令 fc-list 查看你系统的字体
font:
  size: 10
  normal:
    family: JetBrainsMono Nerd Font
    # family: WenQuanYi Micro Hei
  #   style: Medium

  bold:
    family: JetBrainsMono Nerd Font
    # family: WenQuanYi Micro Hei
  #   style: Bold

  italic:
    family: JetBrainsMono Nerd Font
    # family: WenQuanYi Micro Hei
  #   style: Italic

  offset:
    x: 0
    y: 0


selection:
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'
  save_to_clipboard: true

key_bindings:
  - { key: V, mods: Shift|Control, action: Paste }
  - { key: C, mods: Shift|Control, action: Copy }
  - { key: U, mods: Shift|Control, action: ScrollPageUp }
  - { key: D, mods: Shift|Control, action: ScrollPageDown }
